FROM centos:7
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    APPUSER='ddclient' \
    APPUID='10007' \
    APPGID='10007'

# Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    chmod 1777 /tmp && \
    . /usr/local/bin/docker-entrypoint-functions.sh && \
    MYUSER=${APPUSER} && \
    MYUID=${APPUID} && \
    MYGID=${APPGID} && \
    ConfigureUser && \
    yum-config-manager --add-repo /tmp/custom.repo && \
    yum install -y epel-release && \
    yum update -y && \
    yum install -y \
      ca-certificates \ 
      openssl \ 
      ssmtp \ 
      mailx \
      perl \
      perl-IO-Socket-SSL \
      perl-IO-Socket-INET6 \
      perl-NetAddr-IP \
      perl-Data-Dumper \
      perl-Test-Simple \
      perl-Test-Requires \
      su-exec \
    && \
    yum install -y \
      make \
      gcc \
      perl-devel \
      libxml2-devel \
      openssl-devel \
      wget \
      git \
      expat-devel \
    && \
    wget https://cpanmin.us/ -O /usr/local/bin/cpanm && \
    chmod +x /usr/local/bin/cpanm && \
    cpanm Data::Validate::IP && \
    git clone --depth 1 https://github.com/wimpunk/ddclient /opt/ddclient && \
    yum history -y undo last && \
    mkdir /docker-entrypoint.d && \
    chmod +x /usr/local/bin/docker-entrypoint.sh && \
    ln -snf /usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh && \
    yum clean all && \
    rm -rf /opt/ddclient/.git \
           /usr/local/bin/cpanm \
           /root/.cpan \
           /tmp/* \
           /var/cache/yum/*  \
           /var/tmp/*
    
### Volume

### Expose ports

### Running User: not used, managed by docker-entrypoint.sh
USER root

### Start ddclient
COPY ./docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["ddclient"]
