FROM digrouz/alpine-s6:latest
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG DDCLIENT_VERSION=''

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    DDCLIENT_VERSION="${DDCLIENT_VERSION}"

# Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    apk upgrade --no-cache && \
    apk add --no-cache --virtual=build-deps \
      autoconf \
      automake \
      make \
      gcc \
      g++ \
      perl-dev \
      libxml2-dev \
      openssl-dev \
      curl \
      wget \
      git \
      expat-dev \
    && \
    apk add --no-cache --virtual=run-deps \
      ca-certificates \
      openssl \
      ssmtp \
      mailx \
      perl \
      perl-http-daemon \
      perl-io-socket-ssl \
      perl-io-socket-inet6 \
      perl-json \
      perl-test-mockmodule \
      perl-test-tcp \
      perl-test-warnings \
      perl-uri \
    && \
    curl -SsL https://cpanmin.us/ -o /usr/local/bin/cpanm && \
    chmod +x /usr/local/bin/cpanm && \
    cpanm Data::Validate::IP && \
    curl -SsL https://github.com/ddclient/ddclient/archive/v${DDCLIENT_VERSION}.tar.gz -o /tmp/ddclient.tar.gz && \
    tar xzf /tmp/ddclient.tar.gz -C /opt && \
    cd /opt/ddclient-${DDCLIENT_VERSION} && \
    ./autogen && \
    ./configure \
      --bindir=/opt/ddclient \
      --sysconfdir=/etc/ddclient \
      --runstatedir=/var/run/ddclient  \
      --localstatedir=/var/cache/ddclient \
    && \
    make && \
    make install && \
    apk del --no-cache --purge \
      build-deps  && \
    rm -rf /opt/ddclient-${DDCLIENT_VERSION} \
           /usr/local/bin/cpanm \
           /root/.cpan \
           /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/*
    
### Volume

### Expose ports

### Running User: not used, managed by docker-entrypoint.sh
USER root

### Start ddclient
ENTRYPOINT ["/init"]
