ARG DDCLIENT_VERSION='3.10.0_2'

FROM centos:7 AS su-exec-builder

RUN set -x && \
    yum update -y && \
    yum install -y \
      gcc \
      make \
      git \
    && \
    git clone --depth 1 https://github.com/ncopa/su-exec.git /opt/su-exec && \
    cd /opt/su-exec && \
    make

FROM centos:7
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG DDCLIENT_VERSION

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    APPUSER='ddclient' \
    APPUID='10007' \
    APPGID='10007' \
    DDCLIENT_VERSION="${DDCLIENT_VERSION}"

# Copy config files
COPY --from=su-exec-builder /opt/su-exec/su-exec /usr/local/bin/su-exec
COPY root/ /

### Install Application
RUN set -x && \
    chmod 1777 /tmp && \
    . /usr/local/bin/docker-entrypoint-functions.sh && \
    MYUSER=${APPUSER} && \
    MYUID=${APPUID} && \
    MYGID=${APPGID} && \
    ConfigureUser && \
    yum install -y epel-release && \
    yum update -y && \
    yum install -y \
      ca-certificates \
      openssl \
      ssmtp \
      mailx \
      perl \
      perl-IO-Socket-SSL \
      perl-IO-Socket-INET6 \
      perl-NetAddr-IP \
      perl-Data-Dumper \
      perl-Test-Simple \
      perl-Test-Requires \
    && \
    yum install -y \
      automake \
      make \
      gcc \
      perl-devel \
      libxml2-devel \
      openssl-devel \
      curl \
      wget \
      git \
      expat-devel \
    && \
    curl -SsL https://cpanmin.us/ -o /usr/local/bin/cpanm && \
    chmod +x /usr/local/bin/cpanm && \
    cpanm Data::Validate::IP && \
    curl -SsL https://github.com/ddclient/ddclient/archive/v${DDCLIENT_VERSION}.tar.gz -o /tmp/ddclient.tar.gz && \
    tar xzf /tmp/ddclient.tar.gz -C /opt && \
    mv /opt/ddclient-${DDCLIENT_VERSION} /opt/ddclient && \
    yum history -y undo last && \
    mkdir /docker-entrypoint.d && \
    chmod +x /usr/local/bin/docker-entrypoint.sh && \
    ln -snf /usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh && \
    yum clean all && \
    rm -rf /opt/ddclient/.git \
           /usr/local/bin/cpanm \
           /root/.cpan \
           /tmp/* \
           /var/cache/yum/*  \
           /var/tmp/*
    
### Volume

### Expose ports

### Running User: not used, managed by docker-entrypoint.sh
USER root

### Start ddclient
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["ddclient"]
