---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ddclient.fullname" . }}-secret-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: ddclient
type: Opaque
stringData:
  ddclient.conf: {{- toYaml .Values.config.ddclientConf | nindent 2 }}
