---
apiVersion: apps/v1
kind: Secret
metadata:
  name: {{ include "ddclient.fullname" . }}-secret-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: ddclient
type: Opaque
data:
  ddclient.conf: |
    # General config
    daemon=300

    # Router
    usev4=webv4,webv4=ipify-ipv4
